sonar.projectKey=MIABE-HACK-2026
sonar.projectName=DiasporaConnect
sonar.organization=MIABE-HACK-2026
sonar.projectVersion=1.0.0

sonar.sources=.
sonar.exclusions=**/node_modules/**,**/*.log,**/dist/**,**/build/**,**/coverage/**,.git/**,backend/node_modules,contracts/node_modules

sonar.sourceEncoding=UTF-8
sonar.language=html,js,css

sonar.host.url=https://sonarcloud.io
sonar.token=${SONAR_TOKEN}

sonar.html.fileExtensions=html
sonar.js.fileExtensions=js,html

sonar.cloc.skip=true